server:
  port: 9590

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

spring:
  cloud:
    gcp:
      project-id: macy-gcp-2022
      credentials:
        location: file:C:\Users\UK64512\Desktop\GoogleGCPCrdentials\macy-gcp-2022-ff5099601b3d.json
